// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANuL5PCRWA0pL-8LufqvEknhVG5NI5aBo',
    appId: '1:517638528095:android:cd78e3c63d47cc469f4fea',
    messagingSenderId: '517638528095',
    projectId: 'minesweeper-1d35e',
    storageBucket: 'minesweeper-1d35e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-R_-WU7gj9N5t9nqPsAuB4pk03-EtR0A',
    appId: '1:517638528095:ios:df4a126fcca3fd339f4fea',
    messagingSenderId: '517638528095',
    projectId: 'minesweeper-1d35e',
    storageBucket: 'minesweeper-1d35e.appspot.com',
    androidClientId: '517638528095-ift9jro98ccce4ufj2ltcrlobfk37o2c.apps.googleusercontent.com',
    iosClientId: '517638528095-bu7rn9p9dt8othu31vtehlbam4ic0n8d.apps.googleusercontent.com',
    iosBundleId: 'revered.minesweeper.com',
  );

}